### ISSUE TITLE
GEnerating Exception while running this code on eclipse ide

### ISSUE THREAD

**Issue by chandankr151** [peteratt/HDFS-Replication-Simulator#1]
please provide the solution. why i m getting exception when i m  going to compile and run this code.
is there any solution then please provide the solution.. after too much search for hdfs simulator on google i found your page only. that is great but after running this code i got stucked.

please help me out.please..

**Comment by chandankr151** [comment]
![Screenshot from 2020-10-15 12-05-59](https://user-images.githubusercontent.com/65387190/96086109-629ec400-0edf-11eb-80be-03c0e90e3385.png)

**Comment by chandankr151** [comment]
can anyone give me solution for this who knows well

**Comment by peteratt** [comment]
@chandankr151 unfortunately this project is no longer maintained and will be archived. I found some pointers that might help you:

https://hadoop.apache.org/docs/r1.2.1/hdfs_design.html#:~:text=by%20the%20NameNode.-,Data%20Replication,are%20replicated%20for%20fault%20tolerance.
https://www.quora.com/How-is-replication-done-in-Hadoop
